### ISSUE TITLE
Module product_autocompany breaks travis ci test

### ISSUE THREAD

**Issue by duanyp1991** [OCA/multi-company#10]
The module: product_autocompany makes company_id on model(product_template) required 
however the demo data in sale/sale_demo.xml:326 have one record of product with empty company_id.

  This actually is quite normal in a real project, some customized modules might change the standard workflow which make the standard tests fail.

**Comment by pedrobaeza** [comment]
That can be solved providing a migration script (for v7) or post-hook for v8 that fills with one company each empty record.

**Comment by duanyp1991** [comment]
right! I'll create a migration script for that.

**Comment by duanyp1991** [comment]
@pedrobaeza  I just checked the code of odoo,（ migration.py）, it seems that only when we update the module and the version is higher, the migration script will be executed. However in this case , we wanna run the migration script when the module is first installed. Please let me know if I miss anything. Thanks! :)

**Comment by pedrobaeza** [comment]
For v7, if you check for `version is None`, you can execute it in first install. For v8, you have to use a pre or post-init hook. See an example here:

https://github.com/odoomrp/odoomrp-wip/blob/8.0/quality_control_stock/__openerp__.py#L42
https://github.com/odoomrp/odoomrp-wip/blob/8.0/quality_control_stock/__init__.py#L10

**Comment by duanyp1991** [comment]
@pedrobaeza  Thanks very much for you answer. I get how it works for v8.
But for v7, What do you mean by 'version is None'. I checked the code again, the migration only works for the module whose state is "to upgrade" (no 'to install' state). I tried putting the version as none, not working.

**Comment by pedrobaeza** [comment]
Here you can see an example of a migration script with `if not version:` condition that fits for performing at first install (not upgrade):

https://github.com/OCA/account-financial-reporting/blob/7.0/account_financial_report_webkit/migrations/7.0.1.0.2/post-migration.py
