### ISSUE TITLE
[RFC] performances issues on product_multi_company used on huge database

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/multi-company#109]
Hi,

I am using product_multi_company on a very big database containing more than 110.000 products spread over 5 companies.

The problem I am facing is bad performance when accessing product.product model.
The record rule is based on a many2many field but when reading through an inherits relation it is not well optimized. We get huge subqueries with expression `id in`.

We are planning to add a technical field on product template as a string expression of the many2many content.

For exemple= companies_technical = "-1-, -3-, -13-"

The goal is to have the record rule like :

[('companies_technical', 'ilike', str('-' + user.company_id.id + '-')]

The childof in the current record rule will be managed by a search method on the technical field.

We tested this patch and it reduced response time by 6 on some processes.

Does anyone has an opinion on that ?  A better idea ?

I am currently preparing a PR with what we did.

**Comment by Cedric-Pigeon** [comment]
@sbidoul @lmignon

**Comment by pedrobaeza** [comment]
Can `auto_join` help?

**Comment by lmignon** [comment]
@pedrobaeza The problem seems to be related to https://github.com/odoo/odoo/issues/26702
`company_ids` is already declared with `auto_join=True`

**Comment by pedrobaeza** [comment]
OK, I see. Then it's OK to go to that patch. It's similar to the parent_left/parent_right deprecation done on master.

**Comment by sbidoul** [comment]
@pedrobaeza @lmignon @Cedric-Pigeon there is a better solution I think. We can optimize the search for company_ids=False if we have a stored flag 'visible_for_all_companies' that is set to True when company_ids is empty, and use it in the record rule.

**Comment by pedrobaeza** [comment]
OK, that can be another solution that seems cleaner.
