### ISSUE TITLE
[product_multi_company] Unable to export res.company.assignment

### ISSUE THREAD

**Issue by Ark74** [OCA/multi-company#113]
**Module:** product_multi_company
**Odoo:** v10

I'm testing this module, on latest v10.
When trying to export the table res_company_assignment for the products using the product_multi_company module, I'm getting.

`Exception: You can not export the column ID of model res.company.assignment, because the table res_company_assignment is not an ordinary table.`

Is this normal behavior?
or am I hitting a bug somewhere?

**Comment by pedrobaeza** [comment]
Yes, that table is a wildcard view table for being able to select any company where you are on a specific one, as res.company is limited to the current one.

**Comment by Ark74** [comment]
Ok, then how do you update companies for hundreds of products?
Directly at db level?

**Comment by pedrobaeza** [comment]
IDs are exactly the same than the res.company. It's just a visualization trick.
