### ISSUE TITLE
[RFC] account_payment_other_company

### ISSUE THREAD

**Issue by max3903** [OCA/multi-company#170]
Depends: account_invoice_consolidated
License: AGPL-3
Estimation: 12 hours

# Description

Odoo Accounting allows each company in a multi-company environment to register payments for their own invoices. Some holding companies needs to be able to register a payment to a vendor bill of another company and automatically create due to's and to from's based on these transactions.

This module allows you to register a payment using the Due To / Due From journal and select the journal of another company to create the journal entries there.

# Configuration

* On each company, set the Due To/Due From Account and Journal

# Usage

* Go to Accounting > Vendors > Bills
* Create or select an open bill
* Client on Register Payment
* Select the Due TO/Due From journal. The field "Paid By" should show up.
* Select the bank or cash journal of the other company
* Validate

The vendor bill is paid and if you check the other company, you should find a new journal entry in the journal you selected in "Paid By".

# Technical Specifications

## account.payment

- [x] Add a many2one field "Paid By" (other_journal_id) to account.journal.
- [x] Display the field only if journal_id = company_id.due_fromto_payment_journal_id.id
- [x] If the field is displayed, it is required.
- [x] The field filters the journals with:
* type = bank or cash
* company_id != self.env.user.company_id.id

![screenshot from 2019-10-31 09-59-15](https://user-images.githubusercontent.com/939952/67965079-fa1fdf80-fbc6-11e9-896f-1cc52a0fa0bf.png)

- [x] Extend the method action_validate_invoice_payment to:
* call super() and then
* create and post the journal entry in the other journal and in the other company:

Account | Partner | Credit | Debit
-- | -- | -- | --
other_journal_id.company_id.due_from_account_id.id | company_id.partner_id.id | amount |  
other_journal_id.default_debit_account_id.id | partner_id |   | amount

**Comment by pedrobaeza** [comment]
I think this should go in OCA/multi-company or OCA/account-payment, but not here.
