### ISSUE TITLE
When a user switches from one company to another the companies of the related partner are rewritten in stead of amended (partner_multi_company)   

### ISSUE THREAD

**Issue by gbeuning** [OCA/multi-company#182]
Hi,

I'm experiencing some issues with `partner_multi_company` when a user switches from one company to another.

**Use case:**

- User 1 has access to both company A and B.
- The related partner of this user also has access to both company A and B. 
- This user switches from company A to company B.

This results in a `res_users` write action (because `res_users.company_id` is changed). The companies (`company_ids`) of the related partner are now overwritten, containing company B only.
This may lead to unexpected results such as user 1 not showing up anymore in the list of users in the UI when this list is shown for user 2 with active company A.

**Odoo version:**
Tested with Odoo v12 CE, `partner_multi_company` v12.0.1.0.0, `base_multi_company` v12.0.1.0.1

**Proposed solution:**
Adapt `write(self, vals)` in res_users.py 

- Append to `user.partner_id.company_ids` in stead of replacing the list of linked records.
- Take new `visible_for_all_companies` into account.
- It would probably also be better to keep the companies for the related partner synchronized with `res_users.company_ids`.

Something like:
```
    @api.multi
    def write(self, vals):
        res = super(ResUsers, self).write(vals)
        if 'company_id' in vals:
            for user in self.sudo():
                if user.partner_id and not(user.partner_id.visible_for_all_companies) and user.partner_id.company_ids:
                    user.partner_id.company_ids = [(4, vals['company_id'])]       
        if 'company_ids' in vals:
            for user in self.sudo():
                if user.partner_id and not(user.partner_id.visible_for_all_companies) and user.partner_id.company_ids:
                    user.partner_id.company_ids = [(6, 0, vals['company_ids'][0][2])]
        return res
```

**Comment by JordiBForgeFlow** [comment]
I agree with this. @MiquelRForgeFlow can you tackle this one? cc @LoisRForgeFlow

**Comment by MiquelRForgeFlow** [comment]
Done in https://github.com/OCA/multi-company/pull/190

**Comment by MiquelRForgeFlow** [comment]
Can be closed.
