### ISSUE TITLE
product_tax_multicompany_default : Search for taxes by tax_group_id instead of name

### ISSUE THREAD

**Issue by v-garcies** [OCA/multi-company#185]
If you change the name of the taxes like this for example:
- TVA collectée 20,0% (Company A)
- TVA collectée 20,0% (Company B)
- TVA collectée 20,0% (Company C)

The "Propagate Taxes" button does not work.

Instead, I changed "taxes_by_company" function from "ProductTemplate" class to search by taxes group.
Like this : (product.py : line 22)

```
    def taxes_by_company(self, field, company_id, match_tax_ids=None):
        taxes_ids = []
        if match_tax_ids is None:
            taxes_ids = self.env['ir.default'].get(
                'product.template', field, company_id=company_id)
        # If None: return default taxes if []: return empty list
        if not match_tax_ids:
            return isinstance(taxes_ids, list) and taxes_ids or []
        AccountTax = self.env['account.tax']
        for tax in AccountTax.browse(match_tax_ids):
            taxes_ids.extend(AccountTax.search([
                ('tax_group_id', '=', tax.tax_group_id.name),
                ('company_id', '=', company_id)
            ]).ids)
        return taxes_ids
```

**Comment by pedrobaeza** [comment]
That's not valid as you can have several taxes in the same group. A better algorithm would be to look for XML-ID, taking into account that now there are auto-generated XML-IDs following a pattern (`company_` + `template_xml_id`).
