### ISSUE TITLE
[10.0] Broken Travis

### ISSUE THREAD

**Issue by SimoRubi** [OCA/multi-company#188]
Travis CI is broken for 10.0, see https://travis-ci.org/OCA/multi-company/branches.
Is anyone already looking into this?

Thanks

**Comment by rousseldenis** [comment]
@pedrobaeza Do you have a clue as you are the last one who looked into this repo?

**Comment by pedrobaeza** [comment]
It seems a change upstream that restricts permissions that caused this, but we are not working anymore with v10.

**Comment by rousseldenis** [comment]
@pedrobaeza @SimoRubi https://github.com/OCA/multi-company/pull/237 is fixing problem on base_multi_company.

**Comment by pedrobaeza** [comment]
Fix on the way.
