### ISSUE TITLE
SO generated by PO cannot be viewed due to multi-company restrictions

### ISSUE THREAD

**Issue by amirhassan-sprintit** [OCA/multi-company#227]
![image](https://user-images.githubusercontent.com/53554413/85695093-63b5a680-b6e0-11ea-8d91-0c9a6ead278c.png)

When trying to view an SO triggered by a PO from another company in the vendor company, the above error is given. 

The purchasing company needs to be activated in order for the SO to be viewed.

**Comment by pedrobaeza** [comment]
It seems you have the res.partner restricted to a company, which is not valid. You must empty `company_id` field for that record.
