### ISSUE TITLE
Code missing

### ISSUE THREAD

**Issue by nicoclavier** [OCA/multi-company#23]
There is no target model defined here : 
[sales_team.py#L15](https://github.com/OCA/multi-company/blob/9.0/sales_team_multicompany/sales_team.py#L15)
Expecting comodel_name="res.company"

Also here the model isn't defined : 
[sales_team_multicompany_security.xml#L5](https://github.com/OCA/multi-company/blob/9.0/sales_team_multicompany/security/sales_team_multicompany_security.xml#L5)
Expecting : 
[9.0] `<field name="model_id">crm.team</field>`
[8.0] `<field name="model_id">crm.case.section</field>`

**Comment by bodedra** [comment]
@nicoclavier These issue is a invalid for me. Here is reason.

1. https://github.com/odoo/odoo/blob/9.0/addons/sales_team/sales_team.py#L45 these line will set default company. And with these sales_team_multicompany module it just disable default method.
2. model_id is already declared at https://github.com/odoo/odoo/blob/9.0/addons/sales_team/security/sales_team_security.xml#L6 . When we override any attributes, it only required that attribute/field not all.

With above description, we can close these issue.

**Comment by pedrobaeza** [comment]
Yes, closing.
