### ISSUE TITLE
[13] mail_multicompany: Emails do not reach destination without any reason

### ISSUE THREAD

**Issue by Random-nobody** [OCA/multi-company#240]
I have two companies with two websites.

- Company A with Website A
- Company B with Website B

I defined two outgoing mail servers:
- Server A
- Server B

Thanks to the `mail_multicompany` I assigned them to the corresponding companies. When Odoo sends emails it seems like correct mail server is assigned (for example when creating sale order form the Website A it assigns Server A and from Website B assigns Server B). Furthermore Odoo does not throw any error and it looks like emails went through. But they never reach the destination.

And when I leave company field inside mail server empty it is working fine (emails reach the destination) but it is always using the server without company assigned. When both servers do not have company assigned it still working and it is choosing server with higher priority.

I’m also using another OCA addon `mail_outbound_static` but it does not seem to play any role here.

Any ideas how to track down the reason why emails do not reach the destination?

**Comment by thiyok** [comment]
Hi Gumaa,

For me, I can get the email....but it used only the same gateway from Server A for Website A, even if I sent Orders from website B. 

Do you know how can I fix this?

Thank you

Matthias
