### ISSUE TITLE
Improvements in Property Fields UI

### ISSUE THREAD

**Issue by wagnerpereirasp** [OCA/multi-company#25]
Hello,

I've been strugling with Property Fields for a while, they work nicely and they sure add a good option for multi-company environments, however I believe the way they show on the UI could be improved.

Today a user needs to be set to use an specific company, only that way we can see the specific field value, if it's a property. However in a true multi-company environment it is possible that some or maybe a lot of users can access more than 1 company, in those cases they have special functions like creating products that can be used into 1 or more companies, anyway, the problem is that for that user to be able to set each different company information for a propery field, he/she needs to change to every single one of them, navigate to the model & record to modify that information.

I think it would be greate if we could improve the UI for property fields where, if a user has access to more than 1 company, he could see a small table with each company name and be capable to change the data for that property field in only 1 screen.

I tried to find any existing module that could add this functionality, so far no success, and I've not too familiar to do a UI change module yet.

Do you guys agree with this plan of action and is this the correct forum ?

Thanks.
Wagner Pereira

**Comment by pedrobaeza** [comment]
Hi, Wagner,

Your idea sounds pretty good, although the implementation can be a bit tricky, due to record rules restrictions, that can be bypassed making operations with sudo, but that can lead to a lot of side effects if you don't control the sudo propagation.

There's nothing in OCA for now for this. Do you plan to work on an improved widget for this? Take into account that you need to make a widget for each possible field type, because they all can be company dependent.

**Comment by wagnerpereirasp** [comment]
Hi Pedro, 

The idea to improve the User Interface could be used for every property field, something in the Odoo core. 

The user should have access to each company, we could use the field res.users.company_ids to identify how to populate this little table, and sudo to each one of these companies to retrieve/save the proper information. 

I also would like to improve the security rules to filter using this field instead of res.users.company_id, this would allow a more real multi-company environment, I see a future where the res.users.company_id field becames irrelevant, but this is for the future. 

For that we would need to do not only this, but a series of other improvements, like not filtering invoices by the res.users.company_id, instead use the res.users.company_ids and add pre-defined filters per each company in the company_ids list, also make sure all the actions that use the res.users.company_id field use instead the company_id field in each module it was created, allowing the users to create a sale order and assign that sale order to one of the company_ids it has access to, also allowing the record to be changed to a different company while in draft state. 

Anyway, I'm frustrated with the current multi-company solution, I think it can be greatly improved it. 

We plan to pursue these changes to support the l10n_br localization, but this specific UI improvement I mentioned is, so far, beyond my capability. 

Thanks a lot. 

Wagner Pereira 

De: "Pedro M. Baeza" notifications@github.com 
Para: "OCA/multi-company" multi-company@noreply.github.com 
Cc: "Wagner Pereira" wagner.pereira@kmee.com.br, "Author" author@noreply.github.com 
Enviadas: Segunda-feira, 1 de agosto de 2016 11:07:18 
Assunto: Re: [OCA/multi-company] Improvements in Property Fields UI (#25) 

Hi, Wagner, 

Your idea sounds pretty good, although the implementation can be a bit tricky, due to record rules restrictions, that can be bypassed making operations with sudo, but that can lead to a lot of side effects if you don't control the sudo propagation. 

There's nothing in OCA for now for this. Do you plan to work on an improved widget for this? Take into account that you need to make a widget for each possible field type, because they all can be company dependent.

**Comment by pedrobaeza** [comment]
Sorry, but you shouldn't touch record rules. If you want to see multiple things, create a company that is parent of the rest, but you never work in parallel with multiple companies, or you data will mix up, so the access should be one company each time. The case of the properties field can be an exception, as you're defining master data, but to change the whole concept to have at document level a field that defines the company you want to work in and make the rest depends on this is too heavy.

**Comment by wagnerpereirasp** [comment]
Can we do something using parent company ? Like if the user is currently using a parent company we could show the multi company data field for the child company that are included in res.users.company_ids, would that go normaly thru standard security rules ? 

De: "Pedro M. Baeza" notifications@github.com 
Para: "OCA/multi-company" multi-company@noreply.github.com 
Cc: "Wagner Pereira" wagner.pereira@kmee.com.br, "Author" author@noreply.github.com 
Enviadas: Segunda-feira, 1 de agosto de 2016 11:55:29 
Assunto: Re: [OCA/multi-company] Improvements in Property Fields UI (#25) 

Sorry, but you shouldn't touch record rules. If you want to see multiple things, create a company that is parent of the rest, but you never work in parallel with multiple companies, or you data will mix up, so the access should be one company each time. The case of the properties field can be an exception, as you're defining master data, but to change the whole concept to have at document level a field that defines the company you want to work in and make the rest depends on this is too heavy.

**Comment by pedrobaeza** [comment]
Parent company is only for showing information, not for writing/creating
records.

**Comment by wagnerpereirasp** [comment]
What about reworking security rules to allow permission if the access is from a parent company ? 

De: "Pedro M. Baeza" notifications@github.com 
Para: "OCA/multi-company" multi-company@noreply.github.com 
Cc: "Wagner Pereira" wagner.pereira@kmee.com.br, "Author" author@noreply.github.com 
Enviadas: Segunda-feira, 1 de agosto de 2016 12:50:49 
Assunto: Re: [OCA/multi-company] Improvements in Property Fields UI (#25) 

Parent company is only for showing information, not for writing/creating 
records.

**Comment by pedrobaeza** [comment]
That's exactly what a parent company do, but again the problem is the
mixing of data between companies when creating records. You must rework all
the domains in every field. Odoo rely on these record rules to avoid this
mangling with domains.

**Comment by wagnerpereirasp** [comment]
I know my final multi-company idea is radical and should take a long time to be implemented, if so, however focusing on the property field UI only I think its doable, do you ? 

De: "Pedro M. Baeza" notifications@github.com 
Para: "OCA/multi-company" multi-company@noreply.github.com 
Cc: "Wagner Pereira" wagner.pereira@kmee.com.br, "Author" author@noreply.github.com 
Enviadas: Segunda-feira, 1 de agosto de 2016 14:13:30 
Assunto: Re: [OCA/multi-company] Improvements in Property Fields UI (#25) 

That's exactly what a parent company do, but again the problem is the 
mixing of data between companies when creating records. You must rework all 
the domains in every field. Odoo rely on these record rules to avoid this 
mangling with domains.

**Comment by pedrobaeza** [comment]
Yes, it can be, but you need someone to implement it...

**Comment by wagnerpereirasp** [comment]
Yeah, I could make a wizard to an specific field, but to automate a wizard that could be used for every possible property field would be more difficulty, plus I would have to make a way to bring these wizards up somehow, maybe a button besides the property field. 

It would be much simpler if we could change the odoo core for that, instead of creating a wizard just updating the method that calculates the property field read/write to show more than 1 input field when necessary. 

Is this even possible ? 

De: "Pedro M. Baeza" notifications@github.com 
Para: "OCA/multi-company" multi-company@noreply.github.com 
Cc: "Wagner Pereira" wagner.pereira@kmee.com.br, "Author" author@noreply.github.com 
Enviadas: Segunda-feira, 1 de agosto de 2016 14:35:23 
Assunto: Re: [OCA/multi-company] Improvements in Property Fields UI (#25) 

Yes, it can be, but you need someone to implement it...

**Comment by pedrobaeza** [comment]
You can't change the core. You should inherit/hack it.

**Comment by wagnerpereirasp** [comment]
I see, try to extend it's function, I'll give it a try. 

This was a good discussion, my intention was to bring the idea up and have it reviewed and, if luck, find someone else that might have done it already, no luck here ! :) 

Thanks Pedro, I'll keep in touch bringing updates once I start digging in it. 

Wagner Pereira 

De: "Pedro M. Baeza" notifications@github.com 
Para: "OCA/multi-company" multi-company@noreply.github.com 
Cc: "Wagner Pereira" wagner.pereira@kmee.com.br, "Author" author@noreply.github.com 
Enviadas: Segunda-feira, 1 de agosto de 2016 14:46:23 
Assunto: Re: [OCA/multi-company] Improvements in Property Fields UI (#25) 

You can't change the core. You should inherit/hack it.
