### ISSUE TITLE
[13.0] purchase_sale_inter_compan. It does not carry out the warehouse movements correctly when company B takes the same product from two different locations.

### ISSUE THREAD

**Issue by Joaco1980** [OCA/multi-company#332]
It does not carry out the warehouse movements correctly when company B takes the same product from two different locations.

V13.0

1. Generate a purchase order from company A of a product X with 2 units
2. In company B to put stock of product X in two different locations WH / A 1 unit and WH / B another unit.
3. Exit the delivery from both locations.
4. Now in company A, only the entry of one unit appears in the purchase order, the other has left it as pending

**Comment by Joaco1980** [comment]
CORRECTION ---> 1. Generate a purchase order from company **A** of a product X with 2 units

**Comment by pedrobaeza** [comment]
I don't see the relation between purchase/sale and stock. This module is only for the first one.

**Comment by Joaco1980** [comment]
purchase_sale_inter_company/models/stock_picking.py 
This makes the warehouse movements self-validated in the other company
??

**Comment by pedrobaeza** [comment]
Uhm, that's a mix of things in the same module, but I see it was added for commodity and not needing a glue module. Maybe that decision should be reconsidered. Anyways, the issue is registered with your problem. Please, put the summary of the issue in the title as well.
