### ISSUE TITLE
account_invoice_inter_company should we forbid customer to create purchase invoice/refund ?

### ISSUE THREAD

**Issue by sebastienbeau** [OCA/multi-company#335]
**module : account_invoice_inter_company**

**Is your feature request related to a problem?**

In multi-company a customer can create a purchase invoice/refund and this will create a sale invoice/refund for the supplier.
This can create workflow problem.

For example, an accountant can create by error a supplier refund manually (because he receive a mail and didn't notice that the refund is already here automatically) and this will create an new refund in the company of the supplier.
It's not normal that the supplier doesn't control what he invoice and refund. It's the supplier responsibility to decide what he invoice what he refund not the customer.

**Describe the solution you'd like**
We should only synchronize invoice in one way supplier to customer and forbid the creation from the customer of a purchase invoice/refund.

What do you think ? I don't see case where this "feature" is needed.

@alexis-via @bealdav @pedrobaeza @PierrickBrun

**Comment by pedrobaeza** [comment]
I think the idea is that you control both companies and you want to ease the inputs doing the work only once. Maybe you can put an option for disabling this behavior to be opt-out.
