### ISSUE TITLE
[QUESTION] Multi company per tab browser

### ISSUE THREAD

**Issue by Andyeyo** [OCA/multi-company#366]
# Module
base_multi_company 10.0

# Describe
I am using base_multi_company in odoo 10, so I want to know if the module works with Multi company per tab browser, because when I use in the first tab with Company A and the second tab with Company B, Odoo recognizes only the last selected company and the other launch access right error.

**Comment by pedrobaeza** [comment]
No, go to version 13 where that feature is native. Closing as no issue.
