### ISSUE TITLE
[RFC] Product Variants by Company

### ISSUE THREAD

**Issue by lasley** [OCA/multi-company#37]
The intent behind these modules will be to provide a `product.template` that is usable for multiple companies, isolated at the variant level. Paired with [`website_sale_product`](https://github.com/OCA/e-commerce/issues/171), this will allow for multiple companies to share the same product template but still provide a differentiation between them.

The easy side of this will be covered in `product_variant_company`, which will basically just add a `company_id` field to `product.product`. A domain_force will be added to the `product.product` record in order to limit the view & edit of those variants to users of the proper company (or parent company).

The next piece of this puzzle will be in `sale_product_company`, which will provide the logic for handling sales orders that contain products from multiple companies.

My thought on this is that if an order is placed that contains products belonging from multiple companies, it will be immediately split into multiple orders (one per relevant company) in the `action_confirm` method of `sale.order`. 

This means that the order will be one during the quotation phase - which is specifically relevant during `website_sale` processes. As soon as the order is confirmed, it is then split and sent to the relevant parties for processing. This is a strategy very similar the one Amazon.com uses for Marketplace purchases/payments.

From there, each of the sales will take their standard workflow path as defined by the relevant company.

Does anyone have any thoughts on this, or some code that might be useful?

**Comment by pedrobaeza** [comment]
Isn't https://github.com/OCA/multi-company/tree/9.0/product_multi_company enough?

**Comment by lasley** [comment]
I use and love `product_multi_company`, however it is not. I am planning on making a glue module though that will add companies from the variants into the `company_ids` provided by that module in the product template.

The current product => company mapping (namely for website_sale) in Odoo is based purely on the user. E.g.:
* User A company_id is Company A
* Product A company_id is Company B
* User A purchases Product A in E-commerce
* Sale order is generated for Company A

This operation is not changed with the `product_multi_company` module, unfortunately. It is also only operating on the template, vs here I need in in the variant.

My intent here is to allow a customer to be assigned to a top level company (think Amazon), then be able to purchase the same product that is offered from multiple providers (Amazon, Company A, Company B) - all of whom are competing on the same storefront.

**Comment by lasley** [comment]
Also just to note, we'll also make a glue module for `partner_multi_company`. This will automatically assign companies to partners as the sale orders are created. This will allow for the child companies to manage their own customer lists.
