### ISSUE TITLE
Odoo v15 mail_multi_company & mail_template_multi_company

### ISSUE THREAD

**Issue by hb-webdev** [OCA/multi-company#384]
It seems [Odoo 15 migration has gone stale](https://github.com/OCA/multi-company/issues/326#issuecomment-1173072042) but our company would desperately appreciate if maintainers could implement and release `mail_multi_company` on the Odoo store for our Odoo.sh v15 instance. Another one we'd love to have is `mail_template_multi_company` (@Olivier-LAURENT) (though [it seems it's ready to merge](https://github.com/OCA/multi-company/pull/351)). Thank you!!

**Comment by pedrobaeza** [comment]
You can fund the authors/contributors to do such migration. Meanwhile, closing this issue, as the other issue is the one to coordinate the migration.

**Comment by ryanc-me** [comment]
FYI @hb-webdev, `mail_multicompany` is migrated at #403
