### ISSUE TITLE
Multi company email domain + signatures:  New module available

### ISSUE THREAD

**Issue by chrisandrewmann** [OCA/multi-company#415]
When in a multi-company environment, currently Odoo does not provide a way for users to use multiple outgoing email addresses.
Commonly separate companies will have their own email domains and need to have outgoing mail clearly branded as such.
It will also require a specific email signature to match the company.

I have personally researched and tested all commercially available apps claiming to offer this in the official Odoo app store, but found none of them to be satisfactory.

I decided to write my own which combines all the ideas from other apps and some additional concepts which I felt were needed.
It has been in use by one of my clients successfully for around 6 months in production.

I would like to make it available to the OCA but would ask for some help taking my code and adapting it as necessary if you feel it would be of benefit as a new module. I don't have any time to spend on further development of it but I can offer advice / support.

Currently available for V15 and V16, should be possible to backport to V14 also.
Source and screenshots available on request but as mentioned i'd appreciate support in actually getting it into OCA from someone who has done that before. Feel free to get in touch.

Please see below the README file for the app. 

---

# Odoo Multi-Company Email Domain Module

This module allows the Odoo users to Add individual email signature per company.
It also allows users to set a different outgoing email address “per company” that they belong to.
When a user changes their current selected company (using the company switcher in the top right), this will force the system to use their chosen email address and also signature of the respective company.
This allows people who belong to multiple companies within Odoo to represent them independently when sending emails externally.

## Features
- Company specific email addresses per user, per company
- Company specific email signature templates - Set once on the company and automatically used by users
This uses mail.template so able to create placeholders for res.user model
- Overrides mail.catchall.domain by allowing users to set a field on the company for company specific catchall domains
- Hides the "Powered by" Odoo signature added to the footer of emails which normally contains the company name

## PRE-INSTALLATION STEPS

1.	Before installing, ensure you have a recent full backup of your database. The only data that is likely to be replaced however is the email signature. If you wish to keep copies of old user signatures, these should be exported to CSV beforehand.
2.	Copy the module to your addons folder, or ask your developers to deploy it using Odoo.SH.
3.	Login as Admin with developer mode enabled, go to Apps and run “Update” to get latest modules. Find the module by name and install.

## POST-INSTALLATION STEPS AND CONFIGURATION EMAIL SERVERS
1.	Login as Admin. Enable Debug mode
2.	Go to Settings > Technical > Outgoing Mail Servers
3.	Ensure you have setup mail servers for each company email domain correctly and also set the From Filter field to the domain name. This is used by Odoo since V15 to automatically detect the appropriate mail server depending on the sender email address and is essential. There should only be ONE server for each domain you wish to send from.

## COMPANIES – SIGNATURES AND CATCHALL
1.	Go to Settings > Users & Companies > Companies
2.	On each of your companies, go to “Multi-Company Email” tab and choose an Email Signature Template. 
Note: An example file is provided with this module. Your template must be created with the model set res.users (Applies To: Users).
You can use placeholders for all standard user fields for example:
```
<t t-out="object.name"/>
<t t-out="object.phone"/>
<t t-out="object.email"/>
<t t-out="object.company_id.website"/>
```
3.	If you wish to override the standard catchall / notifications domain that Odoo uses, on the company set the Catchall Domain to your company domain. Note: If not set, Odoo will use the standard setting in System Parameters for mail.catchall.domain
4.	Repeat for all your companies

## USERS EMAIL ADDRESSES AND SIGNATURES
1.	Go to Users. For each user click to open them and verify their Default company and Allowed companies are set correctly.
2.	In the top right corner, ensure you have the desired company selected in the company switcher.
3.	For each user, edit their record and go to the Multi-Company Email tab. 
Change the Company Specific Email field to match the currently select company in the company switcher preference.
4.	Repeat all steps for every company listed in the switcher, and for every user on the system
Note: If you wish to export / import these in bulk, you can do so by using the list view of users and exporting in bulk the External ID, Name, Company Specific Email and then repeating for all companies by changing the company switcher one at a time. You will have multiple exported CSV/XLSX sheets to import.
5.	Testing: As admin, click on your OWN currently logged-in user in the list of users, ensure that when you change the company switcher preference, your email address of the related partner record changes and also so does the signature shown in the Preferences tab. If all looks ok, proceed.

## USAGE GUIDE
The module allows sending emails via the chatter as your currently selected company email domain identity, and will use the respective email signature also if set (company dependent).

1.	Ensure you have first setup your companies with signature templates and catchall domains then users emails for ALL companies and users on your Odoo system
2.	In either contacts, leads/opportunities, project tasks or any area that uses the “Chatter”, choose your desired company in the company switcher box (top right)
3.	Use the chatter Send Message as normal to send an email to an external address
4.	Note the email received by the external party will match the chosen company email domain (Sent From) and signature
5.	Note when you click reply on the external email you should see the corresponding company catchall domain is being used (if you set it earlier)

**Comment by yboujraf** [comment]
Dear @chrisandrewmann 

Any news if your module is ported to OCA ?

Best Regards,
Youssef

**Comment by chrisandrewmann** [comment]
Hi @yboujraf 
Sorry no further progress. Was hoping for some assistance from someone who has done this before.
I am considering releasing it for free on the app store soon. Currently available for V15 + V16.

**Comment by yboujraf** [comment]
Dear @chrisandrewmann 

Thanks for the feedback.
It will be great if you could notify me when it will published, otherwise I have no experience to push the project in the OCA then, all the community could follow and enhance the new modules ;-)

Best Regards
