### ISSUE TITLE
base_multi_company - question

### ISSUE THREAD

**Issue by agb80** [OCA/multi-company#43]
I just discover this module and wonder what will be the advantages of use it like foundation for a new multi_company objects besides the traditional odoo method?

Thanks in advance for your answers!

**Comment by pedrobaeza** [comment]
@lasley maybe it's good to indicate in the README that this is for having granular permissions by company or a similar text

**Comment by lasley** [comment]
Hi @agb80 - does the new ReadMe in #65 answer these questions?
