### ISSUE TITLE
Multi Company Partner Performance

### ISSUE THREAD

**Issue by simple-software-lab** [OCA/multi-company#431]
I have installed multi company partner module on an Odoo.sh project with around 500k contacts.  The module has made many screens very slow and I have traced it back to the "res.partner company" record rule.  This rule is for if company_ids in company_id or company_ids is not set. Which makes sense as the standard odoo functionality is not set means "all companies".  I have tried a few things unsuccessfully to speed this up, but it seems the Public User and and the discuss module seem to make it so I can't force every partner into companies.  Any suggestions to speed this up?

**Comment by matteoopenf** [comment]
I think there is no solution, odoo.sh have in generally perfomance problem
