### ISSUE TITLE
[10.0] install Product multi-company  report ' mandatory field is not correctly set'

### ISSUE THREAD

**Issue by jeffery9** [OCA/multi-company#53]
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: res_company_assignment_id - res.company.assignment.id]

**Comment by chafique-delli** [comment]
@pedrobaeza, @lasley , I confirm.

**Comment by pedrobaeza** [comment]
Have you tried after the PR merged this morning #91?

**Comment by chafique-delli** [comment]
@pedrobaeza , yes, I just re-test, it's the same.

**Comment by pedrobaeza** [comment]
OK, then it should be another thing. Well, I haven't faced it and runbot is building correctly. Any PR fixing it is welcome.
