### ISSUE TITLE
Multi-company product variant access error

### ISSUE THREAD

**Issue by HekkiMelody** [OCA/multi-company#585]
## Module
- `base_multi_company`
- `product_multi_company`

## Describe the bug
Users without administrator access have an error when accessing product variants with `company_ids` set, when some of those companies are not active.

## To Reproduce
**Affected versions**:
- 14.0 (Tested on runboat)
- Other versions untested so far

Assuming a DB with demo data such as runboat, with `product_multi_company` installed
1. As admin user, create a product template.
2. In the `Companies` field of the product template, select all 3 companies --> This means that users from any of the 3 companies should be able to see it
3. Even if you only activate company San Francisco, the user can see all 3 companies in the
4. Login as demo user (any user with multi-company access, but without administrator rights), only have company "San Francisco active"
5. Try to access the product template you created earlier --> OK. in the `companies` field only "San Francisco" is shown
6. Try to access the product variant related to the template (from the product variants menu up top, not from the smart button in the product template, they are different views) --> Access error related to trying to access the other 2, inactive companies.

![image](https://github.com/OCA/multi-company/assets/78726989/17f87a86-e2e4-410a-8f9d-3952f4aeb048)

**Expected behavior**
User with only a single company active can see a product variant when the active company is among the allowed companies

**Additional context**

Administrator users can always see all companies even if they don't have them active, so the error is not present. For non-admin users, the error seems to happen when trying to read the field `company_ids` of product.product (and in fact, if the field `company_ids` is removed from the view https://github.com/OCA/multi-company/blob/14.0/product_multi_company/views/product_template_view.xml there is no access error anymore.

Upon inspecting the calls from the browser:

- when reading the `product.template`, only company 1 is returned, even though really multiple companies are set on the fields. The other companies are not shown due to record rules filtering them. This is the correct and expected behaviour
![image](https://github.com/OCA/multi-company/assets/78726989/e5283f09-4fcf-405a-be0e-c3c01bab568e)

- when reading the `product.product`, all companies are returned; the actual error happens when the client makes a further `read` call to read the names of these companies.
![image](https://github.com/OCA/multi-company/assets/78726989/4fbe0f39-d2bc-431a-bca9-20f47beffb31)

My hypothesis is that the problem is due to the nature of `product.product` as a model that uses delegation inheritance. The `company_ids` field is really memorized on `product.template`, and maybe that's why the companies are not being filtered correctly. I haven't had time to investigate further.

**Comment by francesco-ooops** [comment]
cc @pedrobaeza and @rousseldenis as authors/contributors for both modules :)

**Comment by francesco-ooops** [comment]
@pedrobaeza @aleuffre @ilyasProgrammer I can reproduce the error, here are the steps briefly: 

install product_multy_company in a fresh db

1) create 3 companies
2) create product template with 3 companies 
3) assign 2 companies to marc demo
4) try to access product variant with marc demo:

Due to security restrictions, you are not allowed to access 'Companies' (res.company) records.

For some reason, this does not happen in an environment with 2 companies + a product template with 2 companies + marc demo with access to 1 company (this could be the reason why this bug has not been reported earlier)

https://recordit.co/1UVrfH26pm

**Comment by pedrobaeza** [comment]
I have just done that in runboat with no luck:

![image](https://github.com/OCA/multi-company/assets/7165771/a115c47f-6b21-4983-9b38-5b7a64e72cb3)

What is different?

**Comment by francesco-ooops** [comment]
My runboat is baseonly (I only installed product_multi_company)

**Comment by francesco-ooops** [comment]
@pedrobaeza reproduced in v15 too (module does not exist in v16)
