### ISSUE TITLE
[15.0] mail_multicompany default from not being applied

### ISSUE THREAD

**Issue by iTecan** [OCA/multi-company#607]
## Module
mail_multicompany 

## Describe the bug
After installing the module, when we configure 2 smtp servers and send an email, the default mail from parameter is not being applied, being the email from the user the one applied instead

## To Reproduce
**Affected versions**: 15.0

1. Config 2 outgoing mail servers that have different domains (@domain1 and @domain2), with from filter being applied
2. In system parameters, config mail.default.from_filter  and mail.default.from with one domain (default@domain1)
4. Config a user with an email (user@domain1)
5. Send a mail with a user that is from the company that has the mail.default.from (user from domain1)

**Expected behavior**
The from in the email header and the resume on top should be the one applied in mail.default.from and mail.default.from_filter (default@domain1) instead of the user's email (user@domain1)

**Additional context**
We tried using the ir_config_parameter_multi_company (after migration) that is from this repo in branch 14.0 that creates and enviroment for the system parameters per company, but is not being applied either

**Comment by dg18** [comment]
Hello @iTecan,

Do you have any knowledge if this module is having the same issue in 16.0?

**Comment by iTecan** [comment]
Hello @dg18,

Currently we haven't tested this behavior in version 16 so we can't give futher information.
