### ISSUE TITLE
Can I get Odoo 17 Product Multi Company, please from OCA

### ISSUE THREAD

**Issue by UsmanGhias** [OCA/multi-company#685]
Odoo 17 Product Multi Company, Please

**Comment by pedrobaeza** [comment]
Check https://github.com/OCA/multi-company/pull/625, and please don't open issues for this.

**Comment by UsmanGhias** [comment]
Thank You Sir, I'm great supporter of OCA, actually I searched that out but got nowhere! I'll definitely contribute to your community! If ever needed
