### ISSUE TITLE
partner_multi_company: user's partner random existence

### ISSUE THREAD

**Issue by pedrocs-exo** [OCA/multi-company#72]
Hi,
I found a weird bug on the partner_multicompany module: a user's partner is only visible to its Current Company users. Steps to reproduce:
1. Create User 1 and User 2 and set Company A and Company B on Allowed Companies for both. As partners for these users are automatically created, you may as well associate them to Company A and B on the partner form.
2. Log in as User 2, select Company B and navigate to the partners list. You should see a partner named User 1, right? Wrong, it's not there!
3. On a different browser log in as User 1 and select Company B as well. Guess what: if you refresh the browser you used on step 2 you will now see User 1.

Can you please confirm? I may be missing something here. FYI I've tested on both my system and the last runbot.

**Comment by pedrobaeza** [comment]
Version?

**Comment by pedrocs-exo** [comment]
Oops, forgot to mention that. Version 10.

**Comment by pedrobaeza** [comment]
@lasley have you experimented this?

**Comment by lasley** [comment]
This one's new to me.

The key is the partner itself. The `company_ids` field is resetting to only the company selected as the primary in the user form. If you navigate to the partner, you can re-add the other company (in the case of Runbot `fourth`), and the partner appears again.

This doesn't happen in console, so I'm assuming there is an `onchange` in play.

**Comment by lasley** [comment]
It's in the [`res.users.write`](https://github.com/odoo/odoo/blob/c7a6409fac80a2d33006ab56fe40d27f2acd2cfd/odoo/addons/base/res/res_users.py#L356). Naturally it's nested deep 😑
