### ISSUE TITLE
product_tax_multicompany_default enhancement: adding a new company

### ISSUE THREAD

**Issue by AlainVanUtterbeeck** [OCA/multi-company#78]
I use product_tax_multicompany_default and currently have 5 companies (thanks to the contributers, it works nicely).
I now need to add a new company: what's the easiest way to get the database correct so that all products are also usable in the new company?
It doesn't need to be an enhancement in the module, possibly an example query in the doc of the module could do the trick, although it might be nice to have it in code.

**Comment by pedrobaeza** [comment]
Sorry, but this is not something to enhance in this module. Use mass_editing.
