### ISSUE TITLE
[11] 

### ISSUE THREAD

**Issue by cesarsc79** [OCA/multi-company#88]
i configure this module:

i go to the menu Settings > Users & Companies > Companies, select one of the companies

BUT 

tab Inter-Company IS NOT

I´ve try in runbot 2minutes ago

WHERE IS THE  inter-company tab?????????

![captura](https://user-images.githubusercontent.com/25187665/37231731-914c70b2-23ec-11e8-9dea-49e3eb285224.PNG)
.

**Comment by nhomar** [comment]
hello.

AFAIK that's an enterprise feature, did you tested on enterprise?

**Comment by pedrobaeza** [comment]
Well, there's a community version, but not yet migrated to v11, so we can close this.
